### ISSUE TITLE
Blog post links not using anchor tags

### ISSUE THREAD

**Issue by JohnPhamous** [MatterhornDev/mountain-top#8]
https://github.com/MatterhornDev/mountain-top/blob/4e029e60d6087dbfc51cda209158b15778722ded/src/components/Posts.js#L18

Is there a reason why you're not using Gatby's `link` component for routing? The post isn't a link so screen readers (or vimium) arn't able to pick it up as a link.

**Comment by Ethan-Arrowood** [comment]
This was a concern of mine. I wanted the entire post card element to be clickable and as far as I could tell the `link` component was only for replacing html `a` tags. Is there a better way to do this that keep the functionality and make its accessible?

**Comment by Ethan-Arrowood** [comment]
Linking this for future ref: https://htmldog.com/guides/html/advanced/links/

I imagine I'll need to make use of https://ui.reach.tech/visually-hidden or the `aria-hidden` attribute

**Comment by Ethan-Arrowood** [comment]
Using this: https://inclusive-components.design/cards/
